accountId: null
connector:
  enabled: true
  identity: true
  network: true
containerImagePath: tenable/cloud-security-kubernetes-cluster-manager
containerImagePullSecrets: []
name: null
pod:
  affinity: {}
  annotations: {}
  labels: {}
  resources:
    limits:
      cpu: "100m"
      memory: "256Mi"
    requests:
      memory: "150Mi"
  tolerations: []
resourceNamePrefix: kubernetes-cluster
sensor:
  containerImagePath: 585051939341.dkr.ecr.us-east-2.amazonaws.com/engserviceimagekubernetesclustersensorrepository
  containerImagePullSecrets: []
  dataPath: "/var/lib/tenable"
  enabled: false
  pod:
    affinity: {}
    annotations: {}
    labels: {}
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "300m"
        memory: "256Mi"
    tolerations: []

